# Generated by Django 5.2.4 on 2025-10-03 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Okul Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schools', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Okul',
                'verbose_name_plural': 'Okullar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sınıf Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.school', verbose_name='Okul')),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('id_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır.', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır. 15 haneye kadar rakam girebilirsiniz.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon Numarası')),
                ('parent_first_name', models.CharField(max_length=50, verbose_name='Veli Adı')),
                ('parent_last_name', models.CharField(max_length=50, verbose_name='Veli Soyadı')),
                ('parent_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır. 15 haneye kadar rakam girebilirsiniz.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Veli Telefon Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.classroom', verbose_name='Sınıf')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school', verbose_name='Okul')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['school', 'classroom', 'last_name', 'first_name'],
                'unique_together': {('school', 'classroom', 'id_number')},
            },
        ),
    ]
