# Generated by Django 5.2.4 on 2025-10-03 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('entry', 'Giriş'), ('exit', 'Çıkış')], max_length=10, verbose_name='Giriş Tipi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Yoklama',
                'verbose_name_plural': 'Yoklamalar',
                'ordering': ['-timestamp'],
            },
        ),
    ]
